// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGu3SLgqfLFm9mxZS5HBU6s218bk5ACgc',
    appId: '1:92125271658:web:b41b850f9c6c1b71e4dc13',
    messagingSenderId: '92125271658',
    projectId: 'smartcard-e4ac9',
    authDomain: 'smartcard-e4ac9.firebaseapp.com',
    storageBucket: 'smartcard-e4ac9.firebasestorage.app',
    measurementId: 'G-ZFYPGQLWHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8VFxFN9gDjRXMdtLOdWirodN-01wg-CY',
    appId: '1:92125271658:android:f6973f5eef20e2f3e4dc13',
    messagingSenderId: '92125271658',
    projectId: 'smartcard-e4ac9',
    storageBucket: 'smartcard-e4ac9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArI4bMVvJOWKJlc-dny12yYY0Jczy4aEI',
    appId: '1:92125271658:ios:8a77d84cc19d158ae4dc13',
    messagingSenderId: '92125271658',
    projectId: 'smartcard-e4ac9',
    storageBucket: 'smartcard-e4ac9.firebasestorage.app',
    iosBundleId: 'com.example.smartCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArI4bMVvJOWKJlc-dny12yYY0Jczy4aEI',
    appId: '1:92125271658:ios:8a77d84cc19d158ae4dc13',
    messagingSenderId: '92125271658',
    projectId: 'smartcard-e4ac9',
    storageBucket: 'smartcard-e4ac9.firebasestorage.app',
    iosBundleId: 'com.example.smartCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGu3SLgqfLFm9mxZS5HBU6s218bk5ACgc',
    appId: '1:92125271658:web:e6048073a3a6c376e4dc13',
    messagingSenderId: '92125271658',
    projectId: 'smartcard-e4ac9',
    authDomain: 'smartcard-e4ac9.firebaseapp.com',
    storageBucket: 'smartcard-e4ac9.firebasestorage.app',
    measurementId: 'G-NLFXZ5MZYC',
  );
}
